name: wander
channels:
  - pytorch
  - defaults
  - http://ticepnexus.ep.petrobras.com.br:8081/nexus/repository/conda-pytorch/
  - http://ticepnexus.ep.petrobras.com.br:8081/nexus/repository/conda-nvidia/
  - http://ticepnexus.ep.petrobras.com.br:8081/nexus/repository/conda-forge/
dependencies:
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiofiles=22.1.0=pyhd8ed1ab_0
  - aiosqlite=0.20.0=pyhd8ed1ab_0
  - alabaster=0.7.13=pyhd8ed1ab_0
  - anyio=3.7.1=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py37hcc03f2d_2
  - arrow=1.2.3=pyhd8ed1ab_0
  - astor=0.8.1=pyh9f0ad1d_0
  - astroid=2.12.11=py37h03978a9_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - autopep8=1.6.0=pyhd8ed1ab_1
  - babel=2.14.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_0
  - bcrypt=3.2.2=py37hcc03f2d_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=22.10.0=py37h03978a9_1
  - blas=2.135=mkl
  - blas-devel=3.9.0=35_h85df5b5_mkl
  - bleach=6.1.0=pyhd8ed1ab_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.0.9=py37hf2a7229_7
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py37ha95fbe2_1
  - chardet=5.0.0=py37h03978a9_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.0.4=py37h03978a9_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cookiecutter=2.6.0=pyhca7485f_0
  - cpuonly=2.0=0
  - cryptography=38.0.2=py37h953a470_1
  - cudatoolkit=11.0.3=hd336c7a_13
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py37hcc03f2d_0
  - dask=2022.2.0=pyhd8ed1ab_0
  - dask-core=2022.2.0=pyhd8ed1ab_0
  - debugpy=1.6.3=py37hf2a7229_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20241021=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - distributed=2022.2.0=py37h03978a9_0
  - docutils=0.19=py37h03978a9_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - flake8=4.0.1=pyhd8ed1ab_2
  - fonttools=4.38.0=py37h51bd9d9_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hdaf720e_2
  - fsspec=2023.1.0=pyhd8ed1ab_0
  - gast=0.5.5=pyhd8ed1ab_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - glib=2.80.2=h0df6a38_0
  - glib-tools=2.80.2=h2f9d560_0
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - grpcio=1.46.3=py37h265e445_0
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - h5py=3.7.0=nompi_py37h24adfc3_101
  - hdf5=1.12.2=nompi_h57737ce_101
  - heapdict=1.0.1=pyhd8ed1ab_1
  - icu=70.1=h0e60522_0
  - idna=3.10=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py37h03978a9_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=6.0.0=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.16.2=pyh025b116_0
  - ipython=7.33.0=py37h03978a9_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_1
  - isoduration=20.11.0=pyhd8ed1ab_0
  - isort=5.11.5=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jellyfish=0.9.0=py37hcc03f2d_1
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py37h03978a9_0
  - jupyter_events=0.6.3=pyhd8ed1ab_1
  - jupyter_server=1.23.4=pyhd8ed1ab_0
  - jupyter_server_fileid=0.9.2=pyhd8ed1ab_0
  - jupyter_server_ydoc=0.8.0=pyhd8ed1ab_0
  - jupyter_ydoc=0.2.4=pyhd8ed1ab_0
  - jupyterlab=3.6.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - jupyterlab_server=2.24.0=pyhd8ed1ab_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyring=23.9.3=py37h03978a9_0
  - kiwisolver=1.4.4=py37h8c56517_0
  - krb5=1.20.1=heb0366b_0
  - lazy-object-proxy=1.7.1=py37hcc03f2d_1
  - lcms2=2.14=h90d422f_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.4=h20038f6_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libcurl=8.1.2=h68f0423_0
  - libdeflate=1.14=hcfcfb64_0
  - libffi=3.5.2=h52bdfb6_0
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.80.2=h0df6a38_0
  - libhwloc=2.11.2=default_hc8275d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblapacke=3.9.0=35_h3ae206f_mkl
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.43=h19919ed_0
  - libprotobuf=3.11.2=h1a1b453_0
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h5a68840_5
  - libsqlite=3.51.1=hf5d6505_1
  - libssh2=1.11.0=h7dfc565_0
  - libtiff=4.4.0=hc4f729c_5
  - libuv=1.51.0=hfd05255_1
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.12.7=h283a6d9_1
  - libzlib=1.2.13=h2466b09_6
  - llvmlite=0.39.1=py37h0c9d48c_0
  - locket=1.0.0=pyhd8ed1ab_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py37hcc03f2d_1
  - matplotlib=3.5.3=py37h03978a9_2
  - matplotlib-base=3.5.3=py37hbaab90a_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - matrixprofile=1.1.10=py37hda49f71_0
  - mccabe=0.6.1=py_1
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2024.2.2=h66d3029_15
  - mkl-devel=2024.2.2=h57928b3_15
  - mkl-include=2024.2.2=h66d3029_15
  - more-itertools=10.0.0=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py37h8c56517_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - natsort=8.4.0=pyhd8ed1ab_0
  - nbclassic=1.1.0=pyhd8ed1ab_0
  - nbclient=0.7.0=pyhd8ed1ab_0
  - nbconvert=7.6.0=pyhd8ed1ab_0
  - nbconvert-core=7.6.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.6.0=pyhd8ed1ab_0
  - nbformat=5.8.0=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - ninja=1.13.2=h477610d_0
  - notebook=6.5.7=pyha770c72_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numba=0.56.3=py37h9c05cb2_0
  - numpy=1.21.6=py37h2830a78_0
  - numpydoc=1.6.0=pyhd8ed1ab_0
  - openjpeg=2.5.0=hc9384bd_1
  - openssl=3.6.0=h725018a_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.3.5=py37h9386db6_0
  - pandoc=3.8.3=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=3.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - pathlib=1.0.1=py37h03978a9_6
  - pathspec=0.12.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=h17e33f8_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py37h42a8222_2
  - pip=24.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.0.0=pyhd8ed1ab_0
  - pluggy=1.0.0=py37h03978a9_3
  - ply=3.11=pyhd8ed1ab_2
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - protobuf=3.11.2=py37he025d50_0
  - psutil=5.9.3=py37h51bd9d9_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=h2466b09_4
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycodestyle=2.8.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.2.0=pyhd8ed1ab_0
  - pyflakes=2.4.0=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pylint=2.15.4=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py37ha54c9ec_1
  - pyod=2.0.2=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.15.7=py37h15e4627_1
  - pyqt5-sip=12.11.0=py37h7f67f24_1
  - pyrsistent=0.18.1=py37hcc03f2d_1
  - pysocks=1.7.1=py37h03978a9_5
  - python=3.7.12=h900ac77_100_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lsp-black=1.1.0=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.0.0=pyhd8ed1ab_0
  - python-lsp-server=1.3.3=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_0
  - python_abi=3.7=4_cp37m
  - pytoolconfig=1.2.5=pyhd8ed1ab_0
  - pytorch=1.13.1=py3.7_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2024.2=pyhd8ed1ab_0
  - pywin32=303=py37hcc03f2d_0
  - pywin32-ctypes=0.2.0=py37h03978a9_1005
  - pywinpty=2.0.8=py37h7f67f24_0
  - pyyaml=6.0=py37hcc03f2d_4
  - pyzmq=24.0.1=py37h7347f05_0
  - qdarkstyle=3.0.2=pyhd8ed1ab_0
  - qstylizer=0.2.3=pyhd8ed1ab_0
  - qt-main=5.15.8=h720456b_6
  - qtawesome=1.3.1=pyh9208f05_0
  - qtconsole=5.2.2=pyhd8ed1ab_1
  - qtconsole-base=5.2.2=pyhd8ed1ab_1
  - qtpy=2.4.2=pyhdecd6ff_0
  - requests=2.32.2=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.8.1=pyhd8ed1ab_0
  - rope=1.11.0=pyhd8ed1ab_0
  - rtree=1.0.1=py37h13cc57e_0
  - scikit-learn=0.21.3=py37h7208079_0
  - scipy=1.7.3=py37hb6553fb_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.3=pyh5737063_0
  - setuptools=59.8.0=py37h03978a9_1
  - sip=6.7.2=py37h7f67f24_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sphinx=5.3.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - spyder=5.2.2=py37h03978a9_3
  - spyder-kernels=2.2.1=py37h03978a9_1
  - sqlite=3.51.1=hdb435a2_1
  - statsmodels=0.13.2=py37h3a130e4_0
  - stumpy=1.11.1=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.13.0=h62715c5_1
  - tblib=3.0.0=pyhd8ed1ab_0
  - tensorboard=1.14.0=py37_0
  - tensorflow=1.14.0=h1f41ff6_0
  - tensorflow-base=1.14.0=py37hc8dfbb8_0
  - tensorflow-estimator=1.14.0=py37h5ca1d4c_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - terminado=0.17.0=pyh08f2357_0
  - text-unidecode=1.3=pyhd8ed1ab_1
  - textdistance=4.6.3=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_3
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - tomlkit=0.12.5=pyha770c72_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - torchaudio=0.13.1=py37_cpu
  - torchvision=0.14.1=py37_cpu
  - tornado=6.1=py37hcc03f2d_3
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - tsfresh=0.19.0=pyhd8ed1ab_0
  - typed-ast=1.5.4=py37hcc03f2d_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - ucrt=10.0.26100.0=h57928b3_0
  - ujson=5.5.0=py37h7f67f24_0
  - unicodedata2=14.0.0=py37hcc03f2d_1
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - watchdog=2.1.9=py37h03978a9_0
  - wcwidth=0.2.10=pyhd8ed1ab_0
  - webcolors=1.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.6.1=pyhd8ed1ab_0
  - werkzeug=2.2.3=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - winpty=0.4.3=4
  - wrapt=1.14.1=py37hcc03f2d_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - y-py=0.5.4=py37had2a638_0
  - yaml=0.2.5=h6a83c73_3
  - yapf=0.33.0=pyhd8ed1ab_1
  - ypy-websocket=0.8.2=pyhd8ed1ab_0
  - zeromq=4.3.4=h0e60522_1
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h2466b09_6
  - zstd=1.5.6=h0ea2cb4_0
variables:
  NUMBA_DISABLE_CUDA: '1'
prefix: C:\Users\UQBU\AppData\Local\miniforge3\envs\wander
